### ISSUE TITLE
Allow multiple entries in static definitions (A, AAAA, TXT, etc.)

### ISSUE THREAD

**Issue by francois09** [francois09/ansible_role_dns#10]
We should include the following syntax:
```
bind__static_ip:
  some: 10.0.0.1
  other:
    - 10.1.0.1
    - 10.1.0.2
```
resulting in:
```
...
some       IN  A   10.0.0.1
other      IN  A   10.1.0.1
other      IN  A   10.1.0.2
...
```
